version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
